### ISSUE TITLE
Unable to start docker Region Error

### ISSUE THREAD

**Issue by Diondk** [iainbullock/tesla-http-proxy-docker#12]
Hi i just added the docker container to my unraid. 

I have added all the variables from the docker_compose as environment variables but i am getting the following error: 

`Traceback (most recent call last):
  File "/app/run.py", line 23, in <module>
    AUDIENCE = {
               ^
KeyError: 'Europe'
Traceback (most recent call last):
  File "/app/run.py", line 23, in <module>
    AUDIENCE = {
               ^
KeyError: 'Europe'
Traceback (most recent call last):
  File "/app/run.py", line 23, in <module>
    AUDIENCE = {
               ^
KeyError: 'Europe'
Configuration Options are:
CLIENT_ID=xxxx
CLIENT_SECRET=Not Shown
DOMAIN=xxxx
PROXY_HOST=192.168.1.233
REGION=Europe
Public keys com.tesla.3p.public-key.pem or selfsigned.pem missing from /share
Generating self-signed SSL certificate
Generating keypair`

Hopefully you can help me fix it so i can enable it again on my HA.

Thank you!

Kind Regards,
Dion

**Comment by Diondk** [comment]
Nevermind it needs to be
Europe, Middle East, Africa
instead of Eurpoe :D
